name: bidrequest-app
services:
  - name: bidrequest-backend
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    source_dir: /
    run_command: heroku-php-apache2
    envs:
      - key: APP_DEBUG
        value: "false"
        scope: RUN_TIME
      - key: DB_HOST
        value: "bidrequest-db-do-user-21638441-0.j.db.ondigitalocean.com"
        scope: RUN_TIME
      - key: DB_PORT
        value: "25060"
        scope: RUN_TIME
      - key: DB_NAME
        value: "defaultdb"
        scope: RUN_TIME
      - key: DB_USER
        value: "doadmin"
        scope: RUN_TIME
      - key: DB_PASSWORD
        value: "AVNS_gX6LEAFH76n9tybmlQJ"
        scope: RUN_AND_BUILD_TIME
        type: SECRET
